### ISSUE TITLE
Typo in READM.md

### ISSUE THREAD

**Issue by legovaer** [appfoundry/jekyll-lightbox#1]
Nice plugin! But I noticed that you have a small typo in your README file. Your example says:

`{% lightbox images/appfoundry.png --data="appfoundry_image_set" --title="The AppFoundry Logo" --alt="This is our logo" --img_style="max-width:80%;" %}`

But if a user uses this example, the image style is not applied. This is because in `lightbox.rb` you look for `--img-style` instead of `--img_style`.

**Comment by bartvandeweerdt** [comment]
You're right. Thanks for noticing!
