### ISSUE TITLE
Style sample?

### ISSUE THREAD

**Issue by kristiannordestgaard** [appfoundry/jekyll-lightbox#3]
Just a request: could you provide a sample CSS style, perhaps something similar to what is seen here? http://lokeshdhakar.com/projects/lightbox2/

**Comment by bartvandeweerdt** [comment]
Hi Kristian. Not sure what you mean. You can use the same styles as shown in the sample. The '--img-style' and '--class' parameters are simply translated to 'style' and 'class' attributes on the <img> element. Hope this helps?
